server:
  port: 8080
  # one of never, always, on_trace_param (deprecated), on_param
  error.include-stacktrace: on-param
  servlet:
    context-path: /geofence
spring:
  config:
    name: geofence
  main:
    banner-mode: off
    web-application-type: servlet
  application:
    name: geofence
  jackson:
    default-property-inclusion: non-empty
    serialization:
      indent-output: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  data.web.pageable.default-page-size: 100

openapi.geoFence.base-path: /api/v2

geofence:
  datasource:
    url: jdbc:h2:mem:geofence
    username: sa
    password: sa
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        hbm2ddl.auto: validate
#       dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect

springdoc:
  api-docs:
    enabled: true
    path: ${openapi.geoFence.base-path}/api-docs
  swagger-ui:
    enabled: true
    path: ${openapi.geoFence.base-path}/swagger-ui.html

---
spring.config.activate.on-profile: dev

geofence:
  datasource:
    url: jdbc:h2:mem:geofence
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl.auto: create

